---
# 
# This package contains the automations and sensors relating to Travis CI
# Based on danrspencer's hassio config: https://github.com/danrspencer/hass-config/blob/master/configuration/package/build_ci.yaml
#

- alias: System Travis Build Status
  trigger:
    - platform: state
      entity_id: sensor.travis_build_status
      from: "started"
      to: "failed"
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Travis CI
        message: Build Failed! {{ "\uD83E\uDD2C" }}
        data:
          url: "https://travis-ci.com/tiberiushunter/hassio-config"
          group: Hassio
          priority: high
          icon_url: "https://github.com/home-assistant/brands/blob/master/core_integrations/travisci/icon.png?raw=true"

- alias: System Travis Build Passed
  trigger:
    - platform: state
      entity_id: sensor.travis_build_status
      from: "started"
      to: "passed"
  action:
    - service: notify.ADMIN_DEVICES
      data:
        title: Travis CI
        message: Build Passed! {{ "\uD83D\uDC4D" }}
        data:
          url: "https://travis-ci.com/tiberiushunter/hassio-config"
          group: Hassio
          priority: high
          icon_url: "https://github.com/home-assistant/brands/blob/master/core_integrations/travisci/icon.png?raw=true"
    - service: hassio.addon_start
      data:
        addon: core_git_pull
