---
# 
# This package contains the automations and sensors relating to Travis CI
# Based on danrspencer's hassio config: https://github.com/danrspencer/hass-config/blob/master/configuration/package/build_ci.yaml
#

- platform: rest
  resource: https://api.travis-ci.com/repo/tiberiushunter%2Fhassio-config/builds?limit=1
  headers:
    Travis-API-Version: 3
  value_template: "{{ value_json.builds[0].state }}"
  name: "Travis Build Status"

- platform: command_line
  name: Git
  command: 'git log -1 --pretty=format:''{"commit": "%H", "abbreviated_commit": "%h", "refs": "%D", "subject": "%s", "author": { "name": "%aN", "email": "%aE", "date": "%aD"}, "commiter": { "name": "%cN", "email": "%cE", "date": "%cD" } }'''
  value_template: >
    {{ value_json.abbreviated_commit }}
  json_attributes:
    - commit
    - refs
    - subject
    - author
    - commiter